# Generated by Django 2.2 on 2019-07-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_history_added_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('attraction_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('duration', models.FloatField(blank=True, max_length=100, null=True)),
                ('no_of_tickets', models.FloatField(blank=True, max_length=100, null=True)),
                ('net_per_ticket', models.FloatField(default=0.0)),
                ('total_net', models.FloatField(default=0.0)),
                ('gross_per_ticket', models.FloatField(default=0.0)),
                ('total_gross', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_guest', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.FloatField(default=0.0)),
                ('payment_due', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_due_date', models.DateField(blank=True, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
        ),
    ]
