# Generated by Django 2.2 on 2019-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='duration',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
