# Generated by Django 2.2 on 2019-07-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0002_auto_20190708_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='issue_date',
        ),
    ]
