# Generated by Django 2.2 on 2019-06-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_carbookingproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_off_time', models.DateTimeField(blank=True, null=True)),
                ('num_days', models.FloatField(blank=True, null=True)),
                ('car_category', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_cars', models.CharField(blank=True, max_length=100, null=True)),
                ('net_per_night', models.FloatField(blank=True, null=True)),
                ('total_net', models.FloatField(blank=True, null=True)),
                ('gross_per_night', models.FloatField(blank=True, null=True)),
                ('total_gross', models.FloatField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
        ),
    ]
