# Generated by Django 2.2 on 2019-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='balance_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='booked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='deposit_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='lead_driver',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='payment_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='rental_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='supplier_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='total_car_rental_gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='total_car_rental_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='vat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
