# Generated by Django 2.2 on 2019-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0003_auto_20190625_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='drop_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='drop_off_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
