# Generated by Django 2.2 on 2019-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0004_auto_20190703_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
