# Generated by Django 2.2 on 2019-07-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_history_added_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_net', models.FloatField(default=0.0)),
                ('flight_net_other', models.FloatField(default=0.0)),
                ('flight_gross', models.FloatField(default=0.0)),
                ('hotel_net', models.FloatField(default=0.0)),
                ('hotel_net_other', models.FloatField(default=0.0)),
                ('hotel_gross', models.FloatField(default=0.0)),
                ('car_net', models.FloatField(default=0.0)),
                ('car_net_other', models.FloatField(default=0.0)),
                ('car_gross', models.FloatField(default=0.0)),
                ('cruise_net', models.FloatField(default=0.0)),
                ('cruise_net_other', models.FloatField(default=0.0)),
                ('cruise_gross', models.FloatField(default=0.0)),
                ('tour_net', models.FloatField(default=0.0)),
                ('tour_net_other', models.FloatField(default=0.0)),
                ('tour_gross', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
        ),
    ]
