# Generated by Django 2.2 on 2019-07-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='atol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='insurance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='sfc',
            field=models.FloatField(default=0.0),
        ),
    ]
