# Generated by Django 2.2 on 2019-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20190721_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='admin_charges',
            field=models.FloatField(default=0.0),
        ),
    ]
