# Generated by Django 2.2 on 2019-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
    ]
