# Generated by Django 2.2 on 2019-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0003_auto_20190613_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='age_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, default='United Kingdom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
