# Generated by Django 2.2 on 2019-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0004_auto_20190614_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Infant', 'Infant'), ('Kid', 'Kid'), ('Adult', 'Adult')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Master', 'Master')], max_length=100, null=True),
        ),
    ]
