# Generated by Django 2.2 on 2019-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0005_auto_20190614_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age_group',
            field=models.CharField(blank=True, choices=[('INFANT', 'INFANT'), ('KID', 'KID'), ('ADULT', 'ADULT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Master', 'Master')], max_length=100, null=True),
        ),
    ]
