# Generated by Django 2.2 on 2019-06-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0009_auto_20190615_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
