# Generated by Django 2.2 on 2019-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0010_auto_20190615_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='dep_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='age_group',
            field=models.CharField(blank=True, choices=[('INFANT', 'INFANT'), ('KID', 'KID'), ('CHILD', 'CHILD'), ('ADULT', 'ADULT')], max_length=100, null=True, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, default='United Kingdom', max_length=100, null=True, verbose_name='Nationality'),
        ),
    ]
