# Generated by Django 2.2 on 2019-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0011_auto_20190615_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booking_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='booking_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
