# Generated by Django 2.2 on 2019-06-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0015_auto_20190627_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='Flight',
            new_name='flight',
        ),
    ]
