# Generated by Django 2.2 on 2019-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0016_auto_20190628_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='arr_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='dep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='arr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='dep_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
