# Generated by Django 2.2 on 2019-06-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0017_auto_20190628_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
