# Generated by Django 2.2 on 2019-06-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_auto_20190630_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('room_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('board_basis', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_nights', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('star_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_add', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('no_rooms', models.FloatField(blank=True, null=True)),
                ('net_per_night', models.FloatField(blank=True, null=True)),
                ('net_per_stay', models.FloatField(blank=True, null=True)),
                ('gross_per_night', models.FloatField(blank=True, null=True)),
                ('gross_per_stay', models.FloatField(blank=True, null=True)),
                ('total_net', models.FloatField(blank=True, null=True)),
                ('total_gross', models.FloatField(blank=True, null=True)),
                ('special_offer', models.FloatField(blank=True, null=True)),
                ('lead_guest', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.FloatField(default=0.0)),
                ('payment_due', models.FloatField(default=0.0)),
                ('balance_due_date', models.DateField(blank=True, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
        ),
    ]
