# Generated by Django 2.2 on 2019-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
