# Generated by Django 2.2 on 2019-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_line', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('cruise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_port', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('dep_date', models.DateField(blank=True, null=True)),
                ('dep_time', models.DateField(blank=True, max_length=100, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.CharField(blank=True, max_length=100, null=True)),
                ('return_port', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('num_rooms', models.IntegerField(blank=True, null=True)),
                ('state_room', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('num_guests', models.IntegerField(blank=True, default=0, null=True)),
                ('net_per_night', models.FloatField(blank=True, null=True)),
                ('net_per_stay', models.FloatField(blank=True, null=True)),
                ('gross_per_night', models.FloatField(blank=True, null=True)),
                ('gross_per_stay', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.FloatField(default=0.0)),
                ('payment_due', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_due_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
