# Generated by Django 2.2 on 2019-07-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruisebooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruisehire',
            name='issue_date',
        ),
    ]
