# Generated by Django 2.2 on 2019-07-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruisebooking', '0003_cruisehire_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruisehire',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
