# Generated by Django 2.2 on 2019-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisebooking', '0004_auto_20190704_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisehire',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cruisehire',
            name='num_guests',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cruisehire',
            name='num_rooms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
