# Generated by Django 2.2 on 2019-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBookingProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
    ]
