# Generated by Django 2.2 on 2019-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_carbookingproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbookingproxy',
            options={'verbose_name': 'Car Booking'},
        ),
    ]
