# Generated by Django 2.2 on 2019-06-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_booking_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_agent',
        ),
    ]
