# Generated by Django 2.2 on 2019-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted')], default=1),
            preserve_default=False,
        ),
    ]
