# Generated by Django 2.2 on 2019-07-03 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='added_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
