# Generated by Django 2.2 on 2019-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_paymentreceived_paymentsmade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='content',
        ),
        migrations.AddField(
            model_name='notes',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
